# Generated by Django 5.0 on 2023-12-12 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('nick_name', models.CharField(blank=True, max_length=85)),
                ('date_of_birth', models.DateField()),
            ],
        ),
    ]
